// Auto-generated by scripts/generate-figures.mjs — do not edit manually
export const figures = [
  {
    "id": "sakura-star-wand",
    "name": "Sakura with Star Wand",
    "series": "Cardcaptor Cuties",
    "manufacturer": "DreamForge Studio",
    "scale": "1/7 Scale PVC",
    "releaseDate": "2024-06",
    "image": "https://placekitten.com/480/640",
    "caption": "Placeholder image—replace with your own magical photo!",
    "description": "A limited edition release featuring a translucent wand and layers of fluttery ribbons.",
    "tags": [
      "Magical girl",
      "Limited",
      "Pastel"
    ]
  },
  {
    "id": "mecha-idol-twinkle",
    "name": "Twinkle Idol Type-02",
    "series": "Starship Serenade",
    "manufacturer": "Celestial Works",
    "scale": "1/6 Scale ABS",
    "releaseDate": "2023-11",
    "image": "https://placebear.com/480/640",
    "caption": "Swap me with your real figure glam shot!",
    "description": "Metallic gradients, glowing armor plates, and an adorable mic drone companion accompany this idol.",
    "tags": [
      "Idol",
      "Mecha",
      "Hologram"
    ]
  },
  {
    "id": "moonlight-tea-party",
    "name": "Moonlight Tea Party",
    "series": "Dreamscape Stories",
    "manufacturer": "Lumière Atelier",
    "scale": "1/8 Scale Resin",
    "releaseDate": "2022-03",
    "image": "https://placebeard.it/480x640",
    "caption": "Imagine your own serene tea time photo here!",
    "description": "A serene moonlit balcony scene complete with porcelain tea set and luminescent fireflies.",
    "tags": [
      "Diorama",
      "Pastel",
      "Scenery"
    ]
  },
  {
    "id": "re-zero-kara-hajimeru-isekai-seikatsu-rem-luminasta-ameagari-day-sega",
    "name": "Re:Zero kara Hajimeru Isekai Seikatsu - Rem - Luminasta - Ameagari Day (SEGA)",
    "series": "Luminasta",
    "manufacturer": "SEGA",
    "scale": "W=130mm (5.07in)  H=210mm (8.19in)",
    "releaseDate": "04/14/2023",
    "image": "https://static.myfigurecollection.net/upload/pictures/2023/04/03/3531981.jpeg",
    "caption": "Rem Ameagari Day",
    "description": "Rem Ameagari Day"
  }
];

export const wishlist = [
  {
    "id": "mecha-valkyrie-prototype",
    "name": "Valkyrie Prototype Unit",
    "series": "Celestial Aegis",
    "manufacturer": "Astra Armory",
    "scale": "1/6 Scale ABS",
    "releaseDate": "2025-06",
    "image": "https://placebeard.it/480x640?image=8",
    "caption": "Imagine this with real metallic wings shimmering on the shelf!",
    "description": "A dynamic aerial pose featuring articulated armor panels, energy wings, and interchangeable weaponry.",
    "tags": [
      "Mecha",
      "Prototype",
      "Deluxe"
    ]
  },
  {
    "id": "celestial-gala-idol",
    "name": "Celestial Gala Idol",
    "series": "Starship Serenade",
    "manufacturer": "Nova Beats Studio",
    "scale": "1/7 Scale PVC",
    "releaseDate": "2025-02",
    "image": "https://placekitten.com/480/640?image=12",
    "caption": "Dreaming about this dazzling concert pose!",
    "description": "Projected starlight ribbons and layered metallic fabrics make this the ultimate show-stopper.",
    "tags": [
      "Idol",
      "Pre-order",
      "Hologram"
    ]
  },
  {
    "id": "forest-guardian-spirit",
    "name": "Forest Guardian Spirit",
    "series": "Mythic Bloom",
    "manufacturer": "Evergreen Atelier",
    "scale": "1/8 Scale Resin",
    "releaseDate": "2024-09",
    "image": "https://placebear.com/480/640?image=3",
    "caption": "Translucent leaves and glowing familiars—yes please!",
    "description": "An ethereal guardian posed with floating spirit companions and a luminous forest base.",
    "tags": [
      "Nature",
      "Diorama",
      "Limited"
    ]
  }
];
