name = "anime-figure-collection-worker"
main = "_worker.js"
compatibility_date = "2024-06-01"

[assets]
directory = "."

[secrets]
required = [
  "ADMIN_USERNAME",
  "ADMIN_PASSWORD"
]

# Production KV binding
[[kv_namespaces]]
binding = "COLLECTION"
id = "9eb8afadcaa343bcab49e375508533d7"
preview_id = "9eb8afadcaa343bcab49e375508533d7"

# Preview / non-production branch Worker
[env.preview]
name = "anime-figure-collection-worker-preview"

[env.preview.assets]
directory = "."

[env.preview.secrets]
required = [
  "ADMIN_USERNAME",
  "ADMIN_PASSWORD"
]

# Preview KV binding
[[env.preview.kv_namespaces]]
binding = "COLLECTION"
id = "9eb8afadcaa343bcab49e375508533d7"
preview_id = "9eb8afadcaa343bcab49e375508533d7"
