name = "anime-figure-collection-worker"
main = "_worker.js"
compatibility_date = "2024-06-01"

[assets]
directory = "."

[[kv_namespaces]]
binding = "COLLECTION"
id = "REPLACE_WITH_PRODUCTION_COLLECTION_KV_ID"
preview_id = "REPLACE_WITH_PREVIEW_COLLECTION_KV_ID"
