name = "anime-figure-collection-worker"
main = "_worker.js"
compatibility_date = "2024-06-01"

[assets]
directory = "."

# Uncomment and replace the IDs below after creating your KV namespaces.
# Without this binding the Worker falls back to an in-memory store.
[[kv_namespaces]]
binding = "COLLECTION"
id = "9eb8afadcaa343bcab49e375508533d7"
preview_id = "43626cada6e94c6aa89618fd0c78d3e3"